site_name: XPeng G6 — Manual de Usuario
site_url: https://p0nj4.github.io/xpeng-g6-manual/

theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.top
    - search.highlight

plugins:
  - search:
      lang: es

nav:
  - Índice: index.md
  - '1. Hola, amigo de XPENG': cap01-bienvenida.md
  - '2. Perfil del Vehículo': cap02-perfil-vehiculo.md
  - '3. XOS': cap03-xos.md
  - '4. Asistencia de Realidad Virtual en Tiempo Real': cap04-asistencia-realidad-virtual.md
  - '5. Imágenes Inteligentes': cap05-imagen-inteligente.md
  - '6. Asistencia a la conducción': cap06-asistencia-conduccion.md
  - '7. Estacionamiento asistido': cap07-estacionamiento-asistido.md
  - '8. Seguridad activa': cap08-seguridad-activa.md
  - '9. Viajar con tranquilidad': cap09-viaje-seguro.md
  - '10. Entrada y salida': cap10-entrada-salida.md
  - '11. Operación de Conducción': cap11-operacion-conduccion.md
  - '12. Configuración de Confort': cap12-configuracion-confort.md
  - '13. Instrucciones de Carga': cap13-instrucciones-carga.md
  - '14. Mantenimiento Diario': cap14-mantenimiento-diario.md
  - '15. Rescate de Emergencia': cap15-rescate-emergencia.md
  - '16. Información del Vehículo': cap16-informacion-vehiculo.md
